# GitHub Pages Configuration
title: DevOps/SRE Learning Portfolio
description: An 8-week journey to master cloud-native technologies and SRE principles
author: Your Name
email: your.email@example.com

# Jekyll settings for static site
markdown: kramdown
highlighter: rouge

# Use simple permalink structure for static HTML compatibility
permalink: /:title/

# Plugins
plugins:
  - jekyll-seo-tag

# Exclude from processing - keep HTML files as-is
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.html"

# Include assets
include:
  - assets

# Base URL (update for GitHub Pages if needed)
# baseurl: /devops_sre