---
# Local StorageClass for development/testing
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  labels:
    app: mysql
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

---
# AWS EBS StorageClass (example for production)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  labels:
    app: mysql
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true

---
# NFS StorageClass for shared storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  labels:
    app: shared-storage
provisioner: kubernetes.io/no-provisioner
parameters:
  archiveOnDelete: "false"