apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: myapp-production

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

images:
  - name: myapp
    newTag: v1.2.0

replicas:
  - name: myapp
    count: 5

namespace: production

commonLabels:
  environment: production
  team: platform

configMapGenerator:
  - name: myapp-config
    behavior: replace
    literals:
      - APP_ENV=production
      - LOG_LEVEL=warn
      - DATABASE_URL=postgresql://prod-db:5432/myapp_prod

secretGenerator:
  - name: myapp-secret
    behavior: replace
    literals:
      - database_url=postgresql://prod-db:5432/myapp_prod
      - redis_url=redis://prod-redis:6379

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: myapp
    spec:
      template:
        spec:
          containers:
          - name: myapp
            env:
            - name: ENVIRONMENT
              value: production
            - name: LOG_LEVEL
              value: warn
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"

  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: myapp
    spec:
      type: LoadBalancer

  - |-
    apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: myapp-pdb
    spec:
      minAvailable: 3
      selector:
        matchLabels:
          app: myapp

  - |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: myapp-hpa
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: myapp
      minReplicas: 3
      maxReplicas: 10
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 70
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80