apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-chart.fullname" . }}
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "myapp-chart.selectorLabels" . | nindent 4 }}

{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "myapp-chart.fullname" . }}-hpa
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "myapp-chart.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}

{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "myapp-chart.fullname" . }}-pdb
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.podDisruptionBudget.minAvailable "1" }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "myapp-chart.selectorLabels" . | nindent 6 }}
{{- end }}

{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "myapp-chart.fullname" . }}-netpol
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "myapp-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  {{- if .Values.networkPolicy.egress }}
  - Egress
  {{- end }}
  ingress:
  {{- if .Values.networkPolicy.ingress.enabled }}
  - from:
    {{- range .Values.networkPolicy.ingress.from }}
    - {{- if .podSelector }}
      podSelector:
        matchLabels:
          {{- .podSelector.matchLabels | toYaml | nindent 10 }}
      {{- end }}
      {{- if .namespaceSelector }}
      namespaceSelector:
        matchLabels:
          {{- .namespaceSelector.matchLabels | toYaml | nindent 10 }}
      {{- end }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  {{- end }}
{{- end }}